[build]
publish = "public"
command = "hugo --gv --minify"

[context.production.environment]
HUGO_VERSION = "0.52"
HUGO_ENV ="production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.52"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deply.environment]
HUGO_VERSION = "0.52"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"